name: Triage Board Management

on:
  issues:
    types:
      - opened
      - closed
jobs:
  createCard:
    runs-on: ubuntu-20.04
    if: github.event.action == 'opened'
    steps:
      - name: Add New Issues to Issue Triage Board
        uses: peter-evans/create-or-update-project-card@5eacbbd224b7814354861b555cc18a8359e2cebe
        with:
          project-name: Issue Triage
          column-name: Needs Triage
  removeCard:
    runs-on: ubuntu-20.04
    if: github.event.action == 'closed'
    steps:
      - uses: alex-page/github-project-automation-plus@7ffb872c64bd809d23563a130a0a97d01dfa8f43
        with:
          project: Issue Triage
          column: Done
          action: delete
          repo-token: ${{ secrets.COMMIT_TOKEN }}
