name: Triage Board Management

on:
  issues:
    types:
      - opened
      - closed
jobs:
  createCard:
    runs-on: ubuntu-20.04
    if: github.event.action == 'opened'
    steps:
      - name: Add New Issues to Issue Triage Board
        uses: peter-evans/create-or-update-project-card@866533e2ae61f13c35fd1d374049713fab43c729
        with:
          project-name: Issue Triage
          column-name: Needs Triage
  removeCard:
    runs-on: ubuntu-20.04
    if: github.event.action == 'closed'
    steps:
      - uses: alex-page/github-project-automation-plus@1f8873e97e3c8f58161a323b7c568c1f623a1c4d
        with:
          project: Issue Triage
          column: Done
          action: delete
          repo-token: ${{ secrets.COMMIT_TOKEN }}
