on:
  push:
    tags:
      - v*
name: Package Release
env:
  # the name of the repo
  HOME_REPO: usnistgov/OSCAL
  # build-specific environment
  CONTENT_CONFIG_PATH: src/config
  SCHEMATRON_HOME: git-content/schematron
  OSCAL_HOME: git-content/oscal
  OSCAL_CICD_PATH: git-content/oscal/build/ci-cd
  OSCAL_WORKING_PATH: git-content/oscal
  OSCAL_WEBSITE_PATH: git-content/oscal/docs
  OSCAL_SCRATCH_PATH: oscal-scratch
jobs:
  tagged-release:
    name: Package GitHub Release
    runs-on: ubuntu-20.04
    steps:
      # use this for main repo master builds
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
        with:
          path: ${{ env.OSCAL_HOME }}
          submodules: recursive
          token: ${{ secrets.COMMIT_TOKEN }}
      - name: Set env
        run: |
          RELEASE_TAG="${GITHUB_REF#refs/*/}"
          RELEASE_VERSION="${RELEASE_TAG#"v"}"
          RELEASE_NAME="oscal-${RELEASE_VERSION}"
          echo "RELEASE_TAG=${RELEASE_TAG}" >> $GITHUB_ENV
          echo "RELEASE_VERSION=${RELEASE_VERSION}" >> $GITHUB_ENV
          echo "RELEASE_NAME=${RELEASE_NAME}" >> $GITHUB_ENV
      - name: Package Release
        run: |
          bash "${OSCAL_CICD_PATH}/package-release.sh" "${OSCAL_WORKING_PATH}"
          tar -jcvf "${OSCAL_WORKING_PATH}/${RELEASE_NAME}.tar.bz2" -C "${OSCAL_WORKING_PATH}/archive" .
          (cd "${OSCAL_WORKING_PATH}/archive" && zip -r "../${RELEASE_NAME}.zip" .)
      - uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb
        with:
          name: release-artifacts
          path: |
            ${{ env.OSCAL_WORKING_PATH }}/${{ env.RELEASE_NAME }}.tar.bz2
            ${{ env.OSCAL_WORKING_PATH }}/${{ env.RELEASE_NAME }}.zip
          retention-days: 5
      - uses: ncipollo/release-action@a2e71bdd4e7dab70ca26a852f29600c98b33153e
        with:
          name: OSCAL ${{ env.RELEASE_VERSION }} Release
          allowUpdates: false
          draft: true
          generateReleaseNotes: true
          token: ${{ secrets.COMMIT_TOKEN }}
          artifacts: "${{ env.OSCAL_WORKING_PATH }}/*.zip,${{ env.OSCAL_WORKING_PATH }}/*.tar.bz2"
