on:
  push:
    branches:
      - main
      - develop
      - release-**
    paths:
      - '!docs/**'
      - '**.md'
      - '.github/workflows/validate-repo-markdown.yml'
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '!docs/**'
      - '**.md'
      - '.github/workflows/validate-repo-markdown.yml'
  workflow_dispatch:
    branches:
      - main
name: Validate Repo Markdown
env:
  # build-specific environment
  OSCAL_HOME: git-content/oscal
jobs:
  check-skip:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.ci-skip-step.outputs.ci-skip }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: ci-skip-step
        uses: mstachniuk/ci-skip@v1
  validate-repo-markdown:
    name: Validate Repo Markdown Content
    needs: check-skip
    if: ${{ needs.check-skip.outputs.skip == 'false' }}
    runs-on: ubuntu-18.04
    steps:
      # use this for pulls where checkout is anonymous
      - uses: actions/checkout@v2
        with:
          path: ${{ env.OSCAL_HOME }}
          submodules: recursive
      # Setup runtime environment
      # -------------------------
      - name: Get markdown-link-check
        run: |
            sudo npm install -g markdown-link-check
      # Build Artifacts
      # ---------------
      - name: Validate repo Markdown content instances
        run: |
          cd "$OSCAL_HOME"
          # this command will filter out any docs Markdown files, which are checked in a different job
          git ls-files "*/*.md" -z | grep --null-data -v "^docs/" | xargs -0 -n1 markdown-link-check -q -c "build/config/.markdown-link-check/config.json"
