on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'docs/**'
      - '.github/workflows/website.yml'
  workflow_dispatch:
    branches:
      - main
name: Build and Publish Website
env:
  # the name of the repo
  HOME_REPO: usnistgov/OSCAL
  HOME_BRANCH: develop
  # dependency versions
  HUGO_VERSION: 0.83.1
  # build-specific environment
  OSCAL_HOME: git-content/oscal
  OSCAL_WEBSITE_PATH: git-content/oscal/docs
jobs:
  build-and-publish-website:
    name: Build and Publish Website
    runs-on: ubuntu-20.04
    steps:
      # use this for main repo builds on branches
      - name: Checkout main branch
        uses: actions/checkout@v2
        if: ${{ github.repository == env.HOME_REPO && github.ref == format('refs/heads/{0}',env.HOME_BRANCH) }}
        with:
          path: ${{ env.OSCAL_HOME }}
          submodules: recursive
          token: ${{ secrets.COMMIT_TOKEN }}
      - name: Get latest from repo
        if: ${{ github.repository == env.HOME_REPO && github.event_name == 'push' }}
        # This will ensure that any files committed by the previous job, will be updated
        run: |
          git pull --ff-only
        working-directory: ${{ env.OSCAL_HOME }}
      # Setup runtime environment
      # -------------------------
      # Operating System packages
      - name: Update APT package metadata
        run: |
          sudo rm -rf /var/lib/apt/lists/* && sudo apt-get update
#      # Ruby and Bundler
#      - name: Install Ruby and Bundler
#        uses: ruby/setup-ruby@v1
#        with:
#          ruby-version: 2.6 # Not needed with a .ruby-version file
#          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
#          working-directory: ${{ env.OSCAL_WEBSITE_PATH }}
      # Install Hugo
      - name: Install Hugo
        run: |
          wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.deb
          sudo apt-get install ./hugo_extended_${HUGO_VERSION}_Linux-64bit.deb
      - name: Run Hugo
        run: |
            cd "${OSCAL_WEBSITE_PATH}"
            hugo -v --debug --minify
      - name: Check internal links
        uses: untitaker/hyperlink@0.1.15
        with:
          args: ${{ env.OSCAL_WEBSITE_PATH }}/public/ --sources ${{ env.OSCAL_WEBSITE_PATH }}/content --github-actions --check-anchors
      - uses: actions/upload-artifact@v2
        with:
          name: website
          path: |
            ${{ env.OSCAL_WEBSITE_PATH }}/public
          retention-days: 5
#      - name: Run HTMLProofer
#        run: |
#          cd "${OSCAL_WEBSITE_PATH}"
#          bundle exec htmlproofer public/ --check-external-hash --url-swap "https\://pages.nist.gov/OSCAL/:/" --assume-extension --log-level :debug --url-ignore "\/reference\//,/pages.nist.gov\/(?:nist-header-footer|leaveNotice)\/.+/"
#      - name: Run deploy script
#        if: ${{ github.repository == env.HOME_REPO && github.ref == format('refs/heads/{0}',env.HOME_BRANCH) }}
#        run: |
#            cd "$OSCAL_WEBSITE_PATH"
#            git config user.name "Deployment Bot"
#            bash ./deploy.sh --push-only -v -m "Deploying website [ci deploy skip]"