name: Generate CI Documentation

on:
  push:
    branches:
      - "feature-*"
    paths:
      - .github/workflows/**
  workflow_call:
    inputs:
      commit_resources:
        description: 'Commit the resources after generating them. (Requires the access_token to be passed)'
        required: false
        default: false
        type: boolean
    secrets:
      access_token:
        description: 'The access token to use for commits.'
        required: false
  workflow_dispatch:
    branches:
    - main
    - develop
    - "feature-*"
    - "release-*"
    inputs:
      commit_resources:
        description: 'commit the resources after generating them. Requires a PAT defined as secrets.COMMIT_TOKEN'
        required: true
        default: false
        type: boolean

jobs:
  update_ci_documentation:
    runs-on: ubuntu-20.04
    steps:
      - name: Generate CI Documentation
        uses: Compton-NIST/Inspector@v1.2
        with:
          artifact_name: docs_ci
          output_path: build/ci-cd/docs
          file_prefix: OSCAL
          markdown_name: README.md
      - name: Commit Documentation Result (Documents and Diagrams)
        if: github.event.inputs.commit_resources == 'true' || inputs.commit_resources == true
        uses: stefanzweifel/git-auto-commit-action@3ea6ae190baf489ba007f7c92608f33ce20ef04a
        with:
          create_branch: true
          branch: auto-ci-docs-update
          file_pattern: '*.svg *.md'
          disable_globbing: true
          skip_dirty_check: false
          commit_user_name: OSCAL GitHub Actions Bot
          commit_user_email: oscal@nist.gov
          commit_author: OSCAL GitHub Actions Bot <oscal@nist.gov>
          commit_message: Auto publishing updated CI documentation and diagrams.
  create_pr:
    needs: update_ci_documentation
    if: github.event.inputs.commit_resources == 'true' || inputs.commit_resources == true
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Create Pull Request with Updates
        run: gh pr create -B main -H auto-ci-docs-update --title 'Update CI Documentation and Diagrams' --body "Automated update from workflow-generate-ci-documentation workflow, due to workflow file changes."
        env:
          GITHUB_TOKEN: ${{ secrets.COMMIT_TOKEN }}