name: Validate Website Content

on:
  workflow_call:
    inputs:
      site_git_ref:
        description: 'git ref, a SHA commit or branch or tag, for the published HTML content'
        required: true
        default: 'nist-pages'
        type: string
      site_git_ref_path:
        description: 'the subdirectory to check out git ref and check links in website content'
        required: true
        default: 'published'
        type: string
      create_issue:
        description: 'create new GitHub issue if broken links found'
        required: false
        default: false
        type: boolean
jobs:
  schedule-validate-website-links:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Latest
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      with:
        fetch-depth: 0 # this ensures that the tag and commit history are available
    - name: Checkout git ref of published website content
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      with:
        ref: ${{ inputs.site_git_ref }}
        path: ${{ inputs.site_git_ref_path }}
    - name: Check website HTML content links
      id: linkchecker
      uses: lycheeverse/lychee-action@4a5af7cd2958a2282cefbd9c10f63bdb89982d76
      with:
        args: --exclude-file ./build/config/.lycheeignore --verbose --no-progress --accept 200,206,429 './published/**/*.html' --exclude-mail
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Create issue if bad links detected
      if: steps.linkchecker.outputs.exit_code != 0 && inputs.create_issue
      uses: peter-evans/create-issue-from-file@99b87c35610e986ad2034a7b0518a9b3ebea541b
      with:
        title: Scheduled Check of Website Content Found Bad Hyperlinks
        content-filepath: ./lychee/out.md
        labels: |
          bug
          Scope: Documentation
          Scope: Website          
