name: Metaschema Validate Repo Markdown
on:
  workflow_call:
    inputs:
      ignorePattern:
        description: 'a pattern provided to grep for files/directories to ignore'
        required: false
        default: '^docs/'
        type: string
      markdownLinkCheckConfig:
        description: 'the path to the markdown link check config file'
        required: false
        default: 'build/config/.markdown-link-check/config.json'
        type: string
  workflow_dispatch:
    inputs:
      ignorePattern:
        description: 'a pattern provided to grep for files/directories to ignore'
        required: false
        default: '^docs/'
        type: string
      markdownLinkCheckConfig:
        description: 'the path to the markdown link check config file'
        required: false
        default: 'build/config/.markdown-link-check/config.json'
        type: string
jobs:
  validate-repo-markdown:
    name: Validate Repo Markdown
    runs-on: ubuntu-latest
    steps:
    # use this for pulls where checkout is anonymous
    - uses: actions/checkout@v3 # current: dcd71f646680f2efd8db4afa5ad64fdcba30e748
      with:
        submodules: recursive
    # Setup runtime environment
    # -------------------------
    - name: Set up NodeJS
      uses: actions/setup-node@v3 # current: 56337c425554a6be30cdef71bf441f15be286854 
      with:
        node-version-file: 'build/.nvmrc'
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    - name: Setup Dependencies
      run: |
        # NodeJS
        cd "${{ github.workspace }}/build"
        npm install --loglevel verbose
        echo "$PWD/node_modules/.bin/" >> $GITHUB_PATH
    # Build Artifacts
    # ---------------
    - name: Validate repo Markdown content instances
      run: |
        # this command will filter out any docs Markdown files, which are checked in a different job
        git ls-files "*/*.md" -z | grep --null-data -v "${{ inputs.ignorePattern }}" | xargs -0 -n1 markdown-link-check -q -c "${{ inputs.markdownLinkCheckConfig }}"
